# Generated by Django 5.2.12 on 2026-03-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemorySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='会话ID')),
                ('user_name', models.CharField(blank=True, max_length=100, verbose_name='用户名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context_summary', models.TextField(blank=True, verbose_name='上下文摘要')),
            ],
            options={
                'verbose_name': '记忆会话',
                'verbose_name_plural': '记忆会话',
            },
        ),
        migrations.CreateModel(
            name='LocationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='地址')),
                ('analysis_result', models.JSONField(blank=True, default=dict, verbose_name='分析结果')),
                ('score', models.FloatField(default=0.0, verbose_name='评分')),
                ('user_feedback', models.CharField(blank=True, max_length=20, verbose_name='用户反馈')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='memory.memorysession')),
            ],
            options={
                'verbose_name': '选址记忆',
                'verbose_name_plural': '选址记忆',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='知识内容')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='来源')),
                ('relevance_score', models.FloatField(default=0.0, verbose_name='相关性评分')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge', to='memory.memorysession')),
            ],
            options={
                'verbose_name': '知识记忆',
                'verbose_name_plural': '知识记忆',
            },
        ),
        migrations.CreateModel(
            name='ConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手'), ('system', '系统')], max_length=20, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='memory.memorysession')),
            ],
            options={
                'verbose_name': '对话记忆',
                'verbose_name_plural': '对话记忆',
                'ordering': ['created_at'],
            },
        ),
    ]
