# Generated by Django 5.2.12 on 2026-03-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=100, unique=True, verbose_name='报告ID')),
                ('title', models.CharField(max_length=300, verbose_name='报告标题')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='会话ID')),
                ('selected_lat', models.FloatField(verbose_name='选定纬度')),
                ('selected_lng', models.FloatField(verbose_name='选定经度')),
                ('selected_address', models.CharField(blank=True, max_length=500, verbose_name='选定地址')),
                ('total_score', models.FloatField(default=0.0, verbose_name='综合评分')),
                ('report_content', models.JSONField(default=dict, verbose_name='报告内容')),
                ('alternative_locations', models.JSONField(default=list, verbose_name='备选位置')),
                ('pdf_path', models.CharField(blank=True, max_length=500, verbose_name='PDF路径')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '选址报告',
                'verbose_name_plural': '选址报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
