# Generated by Django 5.2.12 on 2026-03-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True, verbose_name='任务ID')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='会话ID')),
                ('latitude', models.FloatField(verbose_name='目标纬度')),
                ('longitude', models.FloatField(verbose_name='目标经度')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='地址')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '分析中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('total_score', models.FloatField(default=0.0, verbose_name='综合评分')),
                ('poi_score', models.FloatField(default=0.0, verbose_name='POI评分')),
                ('traffic_score', models.FloatField(default=0.0, verbose_name='流量评分')),
                ('accessibility_score', models.FloatField(default=0.0, verbose_name='可达性评分')),
                ('exclusion_check', models.BooleanField(default=True, verbose_name='排除区域检查通过')),
                ('analysis_detail', models.JSONField(blank=True, default=dict, verbose_name='分析详情')),
                ('llm_reasoning', models.TextField(blank=True, verbose_name='LLM推理过程')),
                ('rag_context', models.TextField(blank=True, verbose_name='RAG检索上下文')),
                ('kg_entities', models.JSONField(blank=True, default=list, verbose_name='知识图谱实体')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='推荐位置')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '分析任务',
                'verbose_name_plural': '分析任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=100, unique=True, verbose_name='节点ID')),
                ('name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('location', '地点'), ('poi_type', 'POI类型'), ('road', '道路'), ('district', '行政区'), ('factor', '影响因素'), ('standard', '规范标准')], max_length=50, verbose_name='节点类型')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='属性')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '知识图谱节点',
                'verbose_name_plural': '知识图谱节点',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeGraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(max_length=100, verbose_name='关系类型')),
                ('weight', models.FloatField(default=1.0, verbose_name='权重')),
                ('properties', models.JSONField(blank=True, default=dict, verbose_name='属性')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='analysis.knowledgegraphnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='analysis.knowledgegraphnode')),
            ],
            options={
                'verbose_name': '知识图谱边',
                'verbose_name_plural': '知识图谱边',
            },
        ),
    ]
